from datetime import datetime
from pathlib import Path

from src.config import ROOT_DIR

OUTPUT_DIR = ROOT_DIR / "reports" / "stocks"


def generate_stock_report(forecast: dict) -> str:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    symbol = forecast["symbol"]
    name = forecast["name"]
    market = forecast.get("market", "us")
    currency = "₩" if market == "korea" else "$"
    today = datetime.now().strftime("%Y-%m-%d")

    daily = forecast.get("daily", {})
    weekly = forecast.get("weekly", {})
    monthly = forecast.get("monthly", {})

    def fmt_range(r, cur):
        if not r:
            return "N/A"
        return f"{cur}{r.get('low', 0):,.2f} ~ {cur}{r.get('high', 0):,.2f}"

    def direction_emoji(d):
        return {"UP": "🟢", "DOWN": "🔴", "FLAT": "⚪"}.get(d, "⚪")

    # English Report
    en = f"""# {symbol} ({name}) - Daily Forecast Report

**Date**: {today}
**Market**: {"Korea (KRX)" if market == "korea" else "US (NYSE/NASDAQ)"}
**Current Price**: {currency}{forecast.get('last_close', 0):,.2f}
**Last Change**: {forecast.get('change_pct', 0):+.2f}%

---

## Forecast Summary

| Timeframe | Direction | Confidence | Price Range |
|-----------|-----------|------------|-------------|
| Daily (Next Day) | {direction_emoji(daily.get('direction'))} {daily.get('direction', 'N/A')} | {daily.get('confidence', 0):.0%} | {fmt_range(daily.get('price_range'), currency)} |
| Weekly (1 Week) | {direction_emoji(weekly.get('direction'))} {weekly.get('direction', 'N/A')} | {weekly.get('confidence', 0):.0%} | {fmt_range(weekly.get('price_range'), currency)} |
| Monthly (1 Month) | {direction_emoji(monthly.get('direction'))} {monthly.get('direction', 'N/A')} | {monthly.get('confidence', 0):.0%} | {fmt_range(monthly.get('price_range'), currency)} |

## Technical Signals

{forecast.get('tech_summary', 'N/A')}

## AI Analysis

{forecast.get('news_summary', 'No analysis available.')}

### Daily Reasoning
{daily.get('reasoning', 'N/A')}

### Weekly Reasoning
{weekly.get('reasoning', 'N/A')}

### Monthly Reasoning
{monthly.get('reasoning', 'N/A')}

## Catalysts
{chr(10).join('- ' + c for c in forecast.get('key_catalysts', [])) or '- None identified'}

## Risks
{chr(10).join('- ' + r for r in forecast.get('key_risks', [])) or '- None identified'}

---

*Generated by Stock Forecast Platform | {today}*
"""

    # Korean Report
    ko = f"""
---

# {symbol} ({name}) - 일일 전망 리포트

**날짜**: {today}
**시장**: {"한국 (KRX)" if market == "korea" else "미국 (NYSE/NASDAQ)"}
**현재가**: {currency}{forecast.get('last_close', 0):,.2f}
**전일 대비**: {forecast.get('change_pct', 0):+.2f}%

---

## 전망 요약

| 기간 | 방향 | 신뢰도 | 예상 가격 범위 |
|------|------|--------|---------------|
| 일간 (익일) | {direction_emoji(daily.get('direction'))} {daily.get('direction', 'N/A')} | {daily.get('confidence', 0):.0%} | {fmt_range(daily.get('price_range'), currency)} |
| 주간 (1주일) | {direction_emoji(weekly.get('direction'))} {weekly.get('direction', 'N/A')} | {weekly.get('confidence', 0):.0%} | {fmt_range(weekly.get('price_range'), currency)} |
| 월간 (1개월) | {direction_emoji(monthly.get('direction'))} {monthly.get('direction', 'N/A')} | {monthly.get('confidence', 0):.0%} | {fmt_range(monthly.get('price_range'), currency)} |

## 기술적 분석

{forecast.get('tech_summary', 'N/A')}

## AI 분석

{forecast.get('news_summary', '분석 정보 없음.')}

### 일간 전망 근거
{daily.get('reasoning', 'N/A')}

### 주간 전망 근거
{weekly.get('reasoning', 'N/A')}

### 월간 전망 근거
{monthly.get('reasoning', 'N/A')}

## 상승 촉매
{chr(10).join('- ' + c for c in forecast.get('key_catalysts', [])) or '- 해당 없음'}

## 하락 위험
{chr(10).join('- ' + r for r in forecast.get('key_risks', [])) or '- 해당 없음'}

---

*Stock Forecast Platform 생성 | {today}*
"""

    content = en + ko
    safe_symbol = symbol.replace(".", "_")
    output_path = OUTPUT_DIR / f"{today}_{safe_symbol}.md"
    output_path.write_text(content, encoding="utf-8")

    return str(output_path)
